pages.learn = {
    categories: [
        {
            name: 'Bagian 1: Fondasi dan Praproses Citra',
            items: [
                {
                    id: 'modul01',
                    title: 'Pertemuan 1: Kontrak Kuliah dan Gambaran Computer Vision',
                    lines: [
                        '**Pertemuan 1: Kontrak Kuliah dan Gambaran Computer Vision**',
                        '*Citra adalah bahasa kedua setelah teks — belajar membacanya berarti belajar melihat dunia dengan cara baru.*',
                        '---',
                        'Pertemuan ini membuka perjalanan Anda di mata kuliah Computer Vision. Kita akan menyepakati kontrak kuliah, menelusuri RPS 16 pertemuan, dan memahami apa sebenarnya yang dimaksud dengan "membuat komputer melihat".',
                        'Anda juga akan menyiapkan alat kerja utama: repositori GitHub untuk proyek payung **Vision Lab**, lingkungan JavaScript di browser, dan pustaka OpenCV.js yang akan menemani Anda sampai UAS.',
                        '---',
                        '### Mengapa Computer Vision Penting bagi Anda?',
                        'card:Industri Butuh Mata Digital:Sensor kamera murah dan komputer cepat membuat CV dipakai di mana-mana — dari presensi wajah hingga inspeksi produk di pabrik. Tanpa kemampuan ini, Anda kehilangan satu keterampilan inti informatika modern.',
                        'card:Jembatan ke Bidang Lain:CV bukan pulau terpisah. Ia bersinggungan dengan robotika, keamanan siber, simulasi, dan pengembangan web. Menguasainya membuka pintu kolaborasi lintas disiplin.',
                        'card:Etika Data Biometrik:Wajah dan tubuh manusia adalah data sensitif yang dilindungi UU PDP No. 27/2022. Memahami CV berarti juga memahami tanggung jawab hukum dan etis di baliknya.',
                        '---',
                        '### Peta Medan Computer Vision',
                        'Mata kuliah ini dibagi menjadi empat fase besar. Setiap fase membangun di atas fase sebelumnya, dan semuanya bermuara pada satu proyek payung: **Vision Lab**.',
                        'table:[{"Fase": "Bagian 1", "Fokus": "Fondasi dan praproses citra", "Pertemuan": "P1–P4"}, {"Fase": "Bagian 2", "Fokus": "Deteksi, segmentasi, dan UTS", "Pertemuan": "P5–P8"}, {"Fase": "Bagian 3", "Fokus": "Deskripsi, pengenalan pola, pelacakan", "Pertemuan": "P9–P12"}, {"Fase": "Bagian 4", "Fokus": "Aplikasi dan evaluasi akhir", "Pertemuan": "P13–P16"}]',
                        '---',
                        '### Visi Proyek Vision Lab',
                        'Vision Lab adalah satu sistem yang Anda bangun sepanjang semester. Ia adalah laboratorium mini untuk membandingkan pustaka deteksi dan pengenalan wajah yang berjalan di browser — OpenCV.js, face-api.js, MediaPipe — pada berbagai skenario pencahayaan, jarak, dan resolusi.',
                        '```javascript',
                        '// Arsitektur Vision Lab (disederhanakan)\n// Browser (PWA)  →  Cloudflare Worker  →  D1\n//\n// kamera → canvas → inferensi WASM\n//   (OpenCV.js | face-api | MediaPipe)\n//\n// Prinsip: inferensi di klien, citra mentah TIDAK disimpan.\n// Hanya metrik, kotak batas, dan fitur ternormalisasi.\n\nconst VISION_LAB = {\n    nama: \'VisionLab\',\n    stack: [\'JavaScript\', \'OpenCV.js\', \'Canvas API\'],\n    repo: \'vision-lab-<nama-tim>\',\n    prinsip: \'Inferensi di browser, data biometrik minimal\'\n};\n\nconsole.log(\'Proyek:\', VISION_LAB.nama);\nconsole.log(\'Stack:\', VISION_LAB.stack.join(\', \'));',
                        '```',
                        '---',
                        '### Setup Alat Kerja',
                        'Sebelum pertemuan berikutnya, pastikan semua alat berikut sudah terpasang dan berfungsi di komputer Anda. Ini adalah fondasi teknis yang akan dipakai hingga akhir semester.',
                        '```javascript',
                        '// Checklist setup lingkungan kerja\n// 1. Node.js LTS terpasang → cek: node --version\n// 2. Git terpasang → cek: git --version\n// 3. Editor kode (VS Code) + ekstensi Live Server\n// 4. Browser modern (Chrome/Edge/Firefox) dengan DevTools\n// 5. Akun GitHub aktif\n\n// Uji cepat: buat file index.html, lalu jalankan\n// <script src="https://docs.opencv.org/4.x/opencv.js"></script>\n// dan pastikan cv siap dipakai:\n\nfunction cekOpenCV() {\n    if (typeof cv === \'undefined\') {\n        console.log(\'OpenCV.js belum termuat. Periksa koneksi atau path script.\');\n        return false;\n    }\n    console.log(\'OpenCV.js siap. Versi:\', cv.getBuildInformation ? \'terdeteksi\' : \'tidak diketahui\');\n    return true;\n}',
                        '```',
                        '---',
                        '### 3 Konsep Inti Pertemuan Ini',
                        'card:CV adalah Pemrosesan Informasi:Computer Vision bukan sihir. Ia adalah rangkaian operasi matematis atas matriks angka yang mewakili cahaya. Memahami ini menghilangkan rasa takut pada istilah teknis.',
                        'card:Praktik di Browser:Semua praktikum semester ini berjalan di browser dengan JavaScript dan OpenCV.js. Tidak ada instalasi berat, tidak ada dependensi Python — cukup editor, browser, dan rasa ingin tahu.',
                        'card:Etika Sejak Hari Pertama:Data wajah adalah data pribadi. Sejak pertemuan ini, Anda berkomitmen untuk tidak menyimpan citra mentah dan selalu meminta persetujuan subjek.',
                        '---',
                        '### Target Kompetensi Pertemuan 1',
                        'skill:100%:Memahami kontrak kuliah dan RPS 16 pertemuan:Wajib',
                        'skill:95%:Menjelaskan definisi dan ruang lingkup CV:Wajib',
                        'skill:90%:Menyiapkan repositori dan alat kerja:Wajib',
                        'skill:75%:Mengidentifikasi prinsip etika data biometrik:Pengayaan',
                        '---',
                        '### Ringkasan Aktivitas',
                        'table:[{"Aktivitas": "Pembukaan dan kontrak kuliah", "Deskripsi": "Menyepakati aturan, bobot penilaian, dan ekspektasi", "Durasi": "30 menit"}, {"Aktivitas": "Ceramah gambaran CV dan Vision Lab", "Deskripsi": "Menelusuri peta materi dan arsitektur proyek payung", "Durasi": "50 menit"}, {"Aktivitas": "Demo OpenCV.js di browser", "Deskripsi": "Menjalankan skrip pertama yang memuat citra ke canvas", "Durasi": "40 menit"}, {"Aktivitas": "Setup repo dan alat kerja", "Deskripsi": "Membuat repo tim, mengunduh template, memverifikasi lingkungan", "Durasi": "30 menit"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul02',
                    title: 'Pertemuan 2: Pengantar Computer Vision',
                    lines: [
                        '**Pertemuan 2: Pengantar Computer Vision**',
                        '*Komputer tidak melihat wajah — ia melihat angka. Tugas kita membuat angka itu bercerita.*',
                        '---',
                        'Pertemuan ini memperkenalkan konsep dasar Computer Vision: bagaimana citra terbentuk, apa itu piksel dan warna, serta bagaimana JavaScript merepresentasikan citra melalui `canvas` dan `ImageData`.',
                        'Materi ini menjadi fondasi untuk seluruh praktikum berikutnya. Tanpa pemahaman yang kuat di sini, Anda akan kesulitan saat masuk ke praproses dan deteksi objek.',
                        '---',
                        '### Mengapa Memahami Piksel Itu Krusial?',
                        'card:Piksel adalah Unit Cerita:Setiap operasi CV — filter, deteksi tepi, segmentasi — pada akhirnya bekerja pada level piksel. Salah memahami representasi piksel berarti salah memahami seluruh pipeline.',
                        'card:Warna adalah Vektor:Warna bukan sekadar "merah" atau "biru". Ia adalah vektor tiga nilai (R, G, B) atau representasi lain seperti HSV. Memilih ruang warna yang tepat menentukan keberhasilan deteksi.',
                        'card:Canvas adalah Kanvas Digital:Elemen `canvas` HTML5 adalah tempat Anda menggambar, memanipulasi, dan menganalisis citra. Menguasainya adalah syarat mutlak sebelum menyentuh OpenCV.js.',
                        '---',
                        '### Dari Cahaya ke Piksel',
                        'Kamera menangkap cahaya yang dipantulkan objek, lalu mengubahnya menjadi sinyal digital. Setiap titik pada sensor menjadi satu piksel dengan nilai intensitas. Untuk citra berwarna, setiap piksel menyimpan tiga nilai: merah, hijau, dan biru.',
                        '```javascript',
                        '// Representasi citra di JavaScript\n// Citra = matriks angka. Setiap piksel = 4 byte (R, G, B, A).\n\nconst canvas = document.createElement(\'canvas\');\ncanvas.width = 4;\ncanvas.height = 2;\nconst ctx = canvas.getContext(\'2d\');\n\n// Menggambar satu piksel merah di koordinat (0,0)\nconst imageData = ctx.createImageData(1, 1);\nimageData.data[0] = 255; // R\nimageData.data[1] = 0;   // G\nimageData.data[2] = 0;   // B\nimageData.data[3] = 255; // A (opasitas)\nctx.putImageData(imageData, 0, 0);\n\nconsole.log(\'Lebar canvas:\', canvas.width, \'Tinggi:\', canvas.height);\nconsole.log(\'Jumlah piksel:\', canvas.width * canvas.height);',
                        '```',
                        '---',
                        '### Menangkap Citra dari Webcam',
                        'Praktikum pertama Anda adalah menangkap frame dari webcam, menggambarnya ke canvas, lalu membaca nilai pikselnya. Ini adalah langkah awal setiap pipeline CV.',
                        '```javascript',
                        '// Menangkap frame webcam ke canvas\n// HTML: <video id="cam" autoplay></video> <canvas id="frame"></canvas>\n\nasync function mulaiKamera() {\n    const video = document.getElementById(\'cam\');\n    const stream = await navigator.mediaDevices.getUserMedia({ video: true });\n    video.srcObject = stream;\n    await video.play();\n    return video;\n}\n\nfunction ambilFrame(video, canvas) {\n    const ctx = canvas.getContext(\'2d\');\n    canvas.width = video.videoWidth;\n    canvas.height = video.videoHeight;\n    ctx.drawImage(video, 0, 0);\n    return ctx.getImageData(0, 0, canvas.width, canvas.height);\n}\n\n// Hitung rata-rata kecerahan\nfunction rataKecerahan(imageData) {\n    const d = imageData.data;\n    let total = 0;\n    for (let i = 0; i < d.length; i += 4) {\n        total += (d[i] + d[i + 1] + d[i + 2]) / 3;\n    }\n    return total / (d.length / 4);\n}',
                        '```',
                        '---',
                        '### 3 Konsep Inti Pengantar CV',
                        'card:Citra adalah Matriks:Semua operasi CV berakar pada aritmetika matriks. Piksel adalah elemen, dan citra adalah kumpulan elemen yang tersusun dalam grid.',
                        'card:Canvas adalah Jembatan:Canvas menghubungkan kamera, memori, dan algoritma. Ia adalah tempat di mana data citra hidup dan dimanipulasi di browser.',
                        'card:Etika adalah Fondasi:Setiap citra wajah yang Anda proses adalah data pribadi. Persetujuan, minimalisasi data, dan transparansi adalah prinsip yang tidak bisa ditawar.',
                        '---',
                        '### Target Kompetensi Pertemuan 2',
                        'skill:100%:Menjelaskan konsep piksel, warna, dan ruang warna:Wajib',
                        'skill:95%:Menggunakan canvas dan ImageData di JavaScript:Wajib',
                        'skill:90%:Menangkap dan memproses frame webcam:Wajib',
                        'skill:75%:Menerapkan prinsip etika data biometrik:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Eksplorasi piksel", "Deskripsi": "Buat canvas 100x100, isi dengan pola warna, baca dan cetak nilai piksel"}, {"Aktivitas": "Tangkap webcam", "Deskripsi": "Aktifkan kamera, ambil satu frame, tampilkan di canvas, konfirmasi dimensi dan jumlah piksel"}, {"Aktivitas": "Histogram sederhana", "Deskripsi": "Hitung distribusi intensitas R, G, B dari frame yang ditangkap, tampilkan sebagai array"}, {"Aktivitas": "Lembar persetujuan", "Deskripsi": "Susun lembar persetujuan data biometrik untuk subjek yang akan Anda rekam"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul03',
                    title: 'Pertemuan 3: Praproses Citra',
                    lines: [
                        '**Pertemuan 3: Praproses Citra**',
                        '*Citra mentah adalah bahan mentah. Praproses adalah dapur tempat bahan itu diolah menjadi hidangan yang siap dianalisis.*',
                        '---',
                        'Pertemuan ini membahas tahap praproses citra: histogram, filter, threshold, dan transformasi geometri. Praproses adalah langkah yang menentukan kualitas seluruh pipeline CV — sampah masuk, sampah keluar.',
                        'Anda akan mempraktikkan setiap operasi menggunakan OpenCV.js di browser, dan mengukur waktu eksekusi tiap tahap untuk memahami biaya komputasi.',
                        '---',
                        '### Mengapa Praproses Menentukan Segalanya?',
                        'card:Sampah Masuk Sampah Keluar:Detektor terbaik sekalipun akan gagal jika citra input penuh noise atau kontras rendah. Praproses yang tepat menyelamatkan hasil akhir.',
                        'card:Efisiensi adalah Kunci:Setiap operasi punya biaya. Menggabungkan filter yang tepat menghemat milidetik yang berharga, terutama saat inferensi real-time di browser.',
                        'card:Histogram adalah Diagnosis:Histogram memberi Anda gambaran cepat tentang kecerahan, kontras, dan distribusi warna citra. Ia adalah alat diagnosa pertama sebelum operasi apa pun.',
                        '---',
                        '### Histogram dan Ekualisasi',
                        'Histogram adalah grafik frekuensi intensitas piksel. Ekualisasi histogram menyebarkan intensitas agar kontras meningkat, sehingga detail yang tersembunyi menjadi terlihat.',
                        '```javascript',
                        '// Histogram dan ekualisasi dengan OpenCV.js\nfunction histogram(src) {\n    const hists = new cv.MatVector();\n    const channels = [0];\n    const hist = new cv.Mat();\n    const mask = new cv.Mat();\n    const histSize = [256];\n    const ranges = [0, 256];\n    cv.calcHist([src], channels, mask, hist, histSize, ranges);\n    return hist;\n}\n\nfunction ekualisasi(src) {\n    const gray = new cv.Mat();\n    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);\n    const dst = new cv.Mat();\n    cv.equalizeHist(gray, dst);\n    gray.delete();\n    return dst;\n}',
                        '```',
                        '---',
                        '### Filter dan Threshold',
                        'Filter menghaluskan atau menajamkan citra. Threshold memisahkan objek dari latar berdasarkan nilai intensitas. Keduanya adalah operasi dasar yang akan Anda pakai berulang kali.',
                        '```javascript',
                        '// Filter Gaussian dan threshold\nfunction haluskan(src) {\n    const dst = new cv.Mat();\n    const ksize = new cv.Size(5, 5);\n    cv.GaussianBlur(src, dst, ksize, 0, 0, cv.BORDER_DEFAULT);\n    return dst;\n}\n\nfunction thresholdOtsu(src) {\n    const gray = new cv.Mat();\n    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);\n    const dst = new cv.Mat();\n    cv.threshold(gray, dst, 0, 255, cv.THRESH_BINARY + cv.THRESH_OTSU);\n    gray.delete();\n    return dst;\n}',
                        '```',
                        '---',
                        '### Transformasi Geometri',
                        'Transformasi geometri mengubah posisi, ukuran, atau orientasi citra. Operasi ini penting untuk normalisasi input sebelum deteksi.',
                        'table:[{"Operasi": "Resize", "Fungsi": "cv.resize", "Kegunaan": "Menyeragamkan ukuran input detektor"}, {"Operasi": "Rotate", "Fungsi": "cv.rotate", "Kegunaan": "Menyesuaikan orientasi citra"}, {"Operasi": "Warp Affine", "Fungsi": "cv.warpAffine", "Kegunaan": "Koreksi perspektif dan alignment"}, {"Operasi": "Flip", "Fungsi": "cv.flip", "Kegunaan": "Augmentasi data dan koreksi cermin"}]',
                        '---',
                        '### 3 Konsep Inti Praproses',
                        'card:Histogram adalah Peta Intensitas:Histogram memberi Anda gambaran cepat tentang kecerahan, kontras, dan distribusi warna citra. Ia adalah alat diagnosa pertama sebelum operasi apa pun.',
                        'card:Filter adalah Penyaring Noise:Filter Gaussian, median, dan bilateral memiliki karakter berbeda. Memilih filter yang tepat bergantung pada jenis noise yang ingin dihilangkan.',
                        'card:Threshold adalah Pemotong:Threshold mengubah citra grayscale menjadi biner. Ia adalah langkah pertama menuju segmentasi dan deteksi objek.',
                        '---',
                        '### Target Kompetensi Pertemuan 3',
                        'skill:100%:Menghitung dan menganalisis histogram citra:Wajib',
                        'skill:95%:Menerapkan filter dan threshold dengan OpenCV.js:Wajib',
                        'skill:90%:Melakukan transformasi geometri dasar:Wajib',
                        'skill:80%:Mengukur waktu eksekusi tiap tahap praproses:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Pipeline praproses", "Deskripsi": "Bangun fungsi pipeline yang menerima citra mentah dan menghasilkan citra siap deteksi"}, {"Aktivitas": "Eksperimen filter", "Deskripsi": "Bandingkan Gaussian, median, dan bilateral pada citra yang sama, catat perbedaan visual"}, {"Aktivitas": "Threshold adaptif", "Deskripsi": "Uji threshold global vs Otsu vs adaptif pada citra dengan pencahayaan tidak merata"}, {"Aktivitas": "Benchmark waktu", "Deskripsi": "Ukur waktu eksekusi tiap operasi dengan performance.now(), catat hasilnya"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul04',
                    title: 'Pertemuan 4: Praproses Citra Lanjut',
                    lines: [
                        '**Pertemuan 4: Praproses Citra Lanjut**',
                        '*Tepi adalah tempat di mana cerita berubah. Morfologi adalah cara kita merapikan cerita itu.*',
                        '---',
                        'Pertemuan ini melanjutkan praproses dengan deteksi tepi, operasi morfologi, dan pengenalan fitur klasik. Anda juga akan berkenalan dengan detektor klasik Haar cascade sebagai baseline sebelum masuk ke detektor berbasis CNN.',
                        'Materi ini menutup Bagian 1 dan mempersiapkan Anda untuk Bagian 2: deteksi dan segmentasi objek.',
                        '---',
                        '### Mengapa Tepi dan Morfologi Penting?',
                        'card:Tepi adalah Batas Objek:Deteksi tepi mengidentifikasi perubahan intensitas yang tajam, yang biasanya menandai batas antara objek dan latar. Ini adalah langkah awal segmentasi.',
                        'card:Morfologi adalah Pembersih:Operasi morfologi seperti erosi dan dilasi menghilangkan noise kecil, menutup lubang, dan mempertegas bentuk objek.',
                        'card:Baseline Klasik adalah Pembanding:Haar cascade adalah detektor klasik yang cepat dan ringan. Ia menjadi baseline yang berguna saat membandingkan dengan detektor modern.',
                        '---',
                        '### Deteksi Tepi',
                        'Deteksi tepi bekerja dengan menghitung gradien intensitas. Operator Sobel, Canny, dan Laplacian adalah tiga pendekatan yang paling umum.',
                        '```javascript',
                        '// Deteksi tepi Canny\nfunction deteksiTepi(src, lowThresh, highThresh) {\n    const gray = new cv.Mat();\n    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);\n    const edges = new cv.Mat();\n    cv.Canny(gray, edges, lowThresh, highThresh);\n    gray.delete();\n    return edges;\n}\n\n// Sobel gradien X dan Y\nfunction gradienSobel(src) {\n    const gray = new cv.Mat();\n    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);\n    const gx = new cv.Mat();\n    const gy = new cv.Mat();\n    cv.Sobel(gray, gx, cv.CV_32F, 1, 0);\n    cv.Sobel(gray, gy, cv.CV_32F, 0, 1);\n    gray.delete();\n    return { gx, gy };\n}',
                        '```',
                        '---',
                        '### Operasi Morfologi',
                        'Morfologi bekerja pada citra biner atau grayscale. Erosi mengikis objek, dilasi memperbesar, opening menghilangkan noise kecil, dan closing menutup lubang.',
                        '```javascript',
                        '// Morfologi: erosi, dilasi, opening, closing\nfunction morfologi(src, tipe) {\n    const kernel = cv.getStructuringElement(cv.MORPH_RECT, new cv.Size(5, 5));\n    const dst = new cv.Mat();\n    const operasi = {\n        erosi: cv.MORPH_ERODE,\n        dilasi: cv.MORPH_DILATE,\n        opening: cv.MORPH_OPEN,\n        closing: cv.MORPH_CLOSE\n    };\n    cv.morphologyEx(src, dst, operasi[tipe], kernel);\n    kernel.delete();\n    return dst;\n}',
                        '```',
                        '---',
                        '### Detektor Klasik Haar Cascade',
                        'Haar cascade adalah detektor objek klasik yang menggunakan fitur Haar-like dan classifier bertingkat. Ia cepat dan ringan, cocok untuk baseline.',
                        '```javascript',
                        '// Deteksi wajah dengan Haar cascade\n// File: haarcascade_frontalface_default.xml\nasync function deteksiWajahHaar(src) {\n    const classifier = new cv.CascadeClassifier();\n    await classifier.load(\'haarcascade_frontalface_default.xml\');\n    const gray = new cv.Mat();\n    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);\n    const wajah = new cv.RectVector();\n    classifier.detectMultiScale(gray, wajah, 1.1, 3, 0);\n    gray.delete();\n    return wajah;\n}',
                        '```',
                        '---',
                        '### 3 Konsep Inti Praproses Lanjut',
                        'card:Tepi adalah Gradien:Deteksi tepi menghitung perubahan intensitas. Semakin tajam perubahan, semakin kuat tepi yang terdeteksi.',
                        'card:Morfologi adalah Bentuk:Operasi morfologi memanipulasi bentuk objek berdasarkan kernel. Ia adalah alat serbaguna untuk membersihkan citra biner.',
                        'card:Baseline adalah Titik Awal:Haar cascade bukan detektor terbaik, tetapi ia adalah titik awal yang berguna untuk membandingkan peningkatan.',
                        '---',
                        '### Target Kompetensi Pertemuan 4',
                        'skill:100%:Menerapkan deteksi tepi Canny dan Sobel:Wajib',
                        'skill:95%:Menggunakan operasi morfologi untuk pembersihan citra:Wajib',
                        'skill:90%:Menjalankan detektor Haar cascade di browser:Wajib',
                        'skill:80%:Membandingkan hasil detektor klasik dan modern:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Eksperimen Canny", "Deskripsi": "Uji berbagai nilai threshold pada citra yang sama, catat jumlah tepi yang terdeteksi"}, {"Aktivitas": "Pipeline morfologi", "Deskripsi": "Gabungkan threshold dan morfologi untuk membersihkan citra biner dari noise"}, {"Aktivitas": "Deteksi wajah Haar", "Deskripsi": "Jalankan Haar cascade pada frame webcam, tampilkan kotak batas wajah"}, {"Aktivitas": "Baseline run", "Deskripsi": "Catat waktu deteksi dan jumlah wajah terdeteksi, simpan sebagai baseline proyek"}]',
                        '---',
                    ],
                },
            ],
        },

                {
            name: 'Bagian 2: Deteksi, Segmentasi, dan UTS',
            items: [
                {
                    id: 'modul05',
                    title: 'Pertemuan 5: Deteksi dan Segmentasi Objek',
                    lines: [
                        '**Pertemuan 5: Deteksi dan Segmentasi Objek**',
                        '*Deteksi menjawab "di mana", segmentasi menjawab "apa bentuknya". Keduanya adalah mata dan tangan Computer Vision.*',
                        '---',
                        'Pertemuan ini membuka Bagian 2 dengan membahas segmentasi berbasis threshold, region, dan kontur, lalu naik ke detektor klasik dan pengantar detektor berbasis CNN. Anda akan berkenalan dengan metrik evaluasi: IoU, precision, recall, dan F1.',
                        'Materi ini adalah jembatan antara praproses yang sudah Anda kuasai dan deteksi objek yang menjadi inti separuh semester ini.',
                        '---',
                        '### Mengapa Deteksi dan Segmentasi Penting?',
                        'card:Deteksi adalah Fondasi Aplikasi:Presensi wajah, penghitung kendaraan, inspeksi produk — semuanya dimulai dari kemampuan menemukan objek dalam citra. Tanpa deteksi, tidak ada analisis lanjutan.',
                        'card:Segmentasi Memberi Bentuk:Deteksi hanya memberi kotak. Segmentasi memberi tahu piksel mana yang termasuk objek, yang krusial untuk pengukuran dan klasifikasi presisi.',
                        'card:Metrik Mencegah Ilusi:Tanpa IoU, precision, dan recall, Anda tidak tahu seberapa baik detektor Anda. Metrik mengubah "kelihatannya bagus" menjadi angka yang bisa dipercaya.',
                        '---',
                        '### Segmentasi Berbasis Threshold',
                        'Segmentasi threshold memisahkan objek dari latar berdasarkan nilai intensitas. Ia adalah metode segmentasi paling sederhana dan cepat.',
                        '```javascript',
                        '// Segmentasi threshold dan pencarian kontur\nfunction segmentasiThreshold(src, nilai) {\n    const gray = new cv.Mat();\n    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);\n    const biner = new cv.Mat();\n    cv.threshold(gray, biner, nilai, 255, cv.THRESH_BINARY);\n    gray.delete();\n    return biner;\n}\n\nfunction cariKontur(biner) {\n    const kontur = new cv.MatVector();\n    const hierarki = new cv.Mat();\n    cv.findContours(biner, kontur, hierarki, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE);\n    const hasil = [];\n    for (let i = 0; i < kontur.size(); i++) {\n        const luas = cv.contourArea(kontur.get(i));\n        if (luas > 100) hasil.push({ indeks: i, luas });\n    }\n    return hasil;\n}',
                        '```',
                        '---',
                        '### Deteksi Berbasis CNN',
                        'Detektor berbasis CNN seperti SSD, Tiny Detector, dan BlazeFace jauh lebih akurat daripada Haar cascade, dengan biaya komputasi yang lebih tinggi. Di browser, model-model ini berjalan via WebAssembly atau WebGL.',
                        '```javascript',
                        '// Perbandingan detektor: Haar (klasik) vs CNN (modern)\nconst DETEKTOR = {\n    haar: {\n        nama: \'Haar Cascade\',\n        kecepatan: \'sangat cepat\',\n        akurasi: \'sedang\',\n        cocokUntuk: \'baseline, perangkat lemah\'\n    },\n    cnn: {\n        nama: \'BlazeFace / SSD\',\n        kecepatan: \'sedang\',\n        akurasi: \'tinggi\',\n        cocokUntuk: \'aplikasi produksi, presensi\'\n    }\n};\n\nconsole.log(\'Detektor tersedia:\', Object.keys(DETEKTOR));',
                        '```',
                        '---',
                        '### Metrik Evaluasi Deteksi',
                        'IoU mengukur tumpang tindih antara kotak prediksi dan kotak ground truth. Precision, recall, dan F1 merangkum kualitas detektor dalam tiga angka.',
                        'table:[{"Metrik": "IoU", "Rumus": "Area irisan / Area gabungan", "Makna": "Semakin dekat 1, semakin tepat prediksi"}, {"Metrik": "Precision", "Rumus": "TP / (TP + FP)", "Makna": "Dari yang diprediksi positif, berapa yang benar"}, {"Metrik": "Recall", "Rumus": "TP / (TP + FN)", "Makna": "Dari yang sebenarnya positif, berapa yang tertangkap"}, {"Metrik": "F1", "Rumus": "2 × (P × R) / (P + R)", "Makna": "Rata-rata harmonik precision dan recall"}]',
                        '```javascript',
                        '// Menghitung IoU antara dua kotak\nfunction hitungIoU(boxA, boxB) {\n    const x1 = Math.max(boxA.x, boxB.x);\n    const y1 = Math.max(boxA.y, boxB.y);\n    const x2 = Math.min(boxA.x + boxA.w, boxB.x + boxB.w);\n    const y2 = Math.min(boxA.y + boxA.h, boxB.y + boxB.h);\n    const irisan = Math.max(0, x2 - x1) * Math.max(0, y2 - y1);\n    const gabungan = boxA.w * boxA.h + boxB.w * boxB.h - irisan;\n    return irisan / gabungan;\n}\n\nconst a = { x: 0, y: 0, w: 100, h: 100 };\nconst b = { x: 50, y: 50, w: 100, h: 100 };\nconsole.log(\'IoU:\', hitungIoU(a, b).toFixed(3));',
                        '```',
                        '---',
                        '### 3 Konsep Inti Deteksi dan Segmentasi',
                        'card:Threshold adalah Pintu Masuk:Segmentasi threshold adalah langkah pertama dan termurah untuk memisahkan objek dari latar. Ia bekerja baik pada citra dengan kontras tinggi.',
                        'card:Kontur adalah Bentuk:Kontur menghubungkan piksel batas menjadi bentuk yang bisa diukur — luas, keliling, dan momen. Ini adalah representasi objek yang ringkas.',
                        'card:Metrik adalah Kompas:IoU, precision, recall, dan F1 adalah kompas yang menjaga Anda dari ilusi "kelihatannya bagus". Selalu ukur, jangan menebak.',
                        '---',
                        '### Target Kompetensi Pertemuan 5',
                        'skill:100%:Melakukan segmentasi threshold dan ekstraksi kontur:Wajib',
                        'skill:95%:Menjelaskan perbedaan detektor klasik dan CNN:Wajib',
                        'skill:90%:Menghitung IoU, precision, recall, dan F1:Wajib',
                        'skill:80%:Membandingkan dua pustaka deteksi pada satu skenario:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Segmentasi kontur", "Deskripsi": "Segmentasi citra dengan threshold, temukan kontur, hitung luas dan keliling tiap objek"}, {"Aktivitas": "Deteksi dua pustaka", "Deskripsi": "Jalankan Haar cascade dan satu detektor CNN pada frame yang sama, catat hasilnya"}, {"Aktivitas": "Hitung metrik", "Deskripsi": "Anotasi ground truth manual, hitung TP/FP/FN, lalu hitung precision, recall, F1"}, {"Aktivitas": "Run pertama ke D1", "Deskripsi": "Simpan hasil deteksi (latensi, jumlah wajah, metrik) ke basis data melalui Worker"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul06',
                    title: 'Pertemuan 6: Deteksi dan Segmentasi Objek Lanjut',
                    lines: [
                        '**Pertemuan 6: Deteksi dan Segmentasi Objek Lanjut**',
                        '*Landmark adalah peta wajah. Dengan 468 titik, komputer bisa mengenali siapa Anda — dan itu tanggung jawab besar.*',
                        '---',
                        'Pertemuan ini memperdalam deteksi dengan landmark dan representasi wajah. Anda akan menggunakan MediaPipe FaceLandmarker untuk mengekstraksi titik-titik kunci wajah, menormalisasinya, dan menghitung kemiripan antar wajah dengan NCC.',
                        'Materi ini adalah fondasi untuk sistem verifikasi dan presensi yang akan Anda bangun di pertemuan-pertemuan berikutnya.',
                        '---',
                        '### Mengapa Landmark dan Representasi Wajah Penting?',
                        'card:Landmark Memberi Geometri:468 titik landmark memberi komputer pemahaman tentang geometri wajah — posisi mata, hidung, mulut, dan kontur rahang. Ini jauh lebih kaya daripada kotak batas.',
                        'card:Normalisasi Menghilangkan Variasi:Jarak kamera, sudut, dan ukuran wajah berbeda-beda. Normalisasi berbasis IOD membuat representasi konsisten di berbagai kondisi.',
                        'card:Kemiripan adalah Dasar Verifikasi:Verifikasi wajah bekerja dengan mengukur kemiripan antara dua representasi. NCC adalah salah satu metrik kemiripan yang sederhana dan efektif.',
                        '---',
                        '### MediaPipe FaceLandmarker',
                        'MediaPipe FaceLandmarker mendeteksi 468 titik landmark wajah secara real-time di browser. Ia adalah salah satu model modern paling efisien untuk tugas ini.',
                        '```javascript',
                        '// MediaPipe FaceLandmarker (konsep)\n// import { FaceLandmarker } from \'@mediapipe/tasks-vision\';\n\nasync function inisialisasiLandmarker() {\n    const vision = await FilesetResolver.forVisionTasks(\n        \'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/wasm\'\n    );\n    const landmarker = await FaceLandmarker.createFromOptions(vision, {\n        baseOptions: { modelAssetPath: \'face_landmarker.task\' },\n        runningMode: \'VIDEO\',\n        numFaces: 1\n    });\n    return landmarker;\n}\n\nfunction ambilLandmark(landmarker, video, timestamp) {\n    const hasil = landmarker.detectForVideo(video, timestamp);\n    return hasil.faceLandmarks[0] || null;\n}',
                        '```',
                        '---',
                        '### Normalisasi IOD',
                        'Inter-Ocular Distance (IOD) adalah jarak antara kedua mata. Dengan membagi semua koordinat landmark dengan IOD, representasi wajah menjadi invarian terhadap skala.',
                        '```javascript',
                        '// Normalisasi landmark berdasarkan IOD\nfunction normalisasiIOD(landmark) {\n    const mataKiri = landmark[33];\n    const mataKanan = landmark[263];\n    const iod = Math.hypot(\n        mataKanan.x - mataKiri.x,\n        mataKanan.y - mataKiri.y\n    );\n    return landmark.map(p => ({\n        x: (p.x - mataKiri.x) / iod,\n        y: (p.y - mataKiri.y) / iod,\n        z: p.z / iod\n    }));\n}\n\nconsole.log(\'Normalisasi selesai. Jumlah titik:\', normalisasiIOD.length);',
                        '```',
                        '---',
                        '### Kemiripan NCC',
                        'Normalized Cross-Correlation (NCC) mengukur kemiripan antara dua vektor fitur. Nilai mendekati 1 berarti sangat mirip, mendekati 0 berarti tidak mirip.',
                        '```javascript',
                        '// Normalized Cross-Correlation\nfunction ncc(a, b) {\n    const n = Math.min(a.length, b.length);\n    let sumAB = 0, sumA2 = 0, sumB2 = 0;\n    for (let i = 0; i < n; i++) {\n        sumAB += a[i] * b[i];\n        sumA2 += a[i] * a[i];\n        sumB2 += b[i] * b[i];\n    }\n    return sumAB / (Math.sqrt(sumA2) * Math.sqrt(sumB2));\n}\n\nconst fiturA = [0.5, 0.3, 0.8, 0.1];\nconst fiturB = [0.4, 0.35, 0.75, 0.15];\nconsole.log(\'Kemiripan:\', ncc(fiturA, fiturB).toFixed(3));',
                        '```',
                        '---',
                        '### Segmentasi Lanjut',
                        'Segmentasi lanjut mencakup pemisahan objek yang saling menempel, penggunaan watershed, dan segmentasi berbasis model. Di browser, pendekatan paling praktis adalah kombinasi threshold, morfologi, dan kontur.',
                        'table:[{"Metode": "Watershed", "Kelebihan": "Memisahkan objek yang menempel", "Keterbatasan": "Sensitif terhadap marker"}, {"Metode": "GrabCut", "Kelebihan": "Segmentasi foreground-background", "Keterbatasan": "Perlu interaksi pengguna"}, {"Metode": "SAM", "Kelebihan": "Segmentasi universal tanpa latihan", "Keterbatasan": "Berat, butuh WebGL"}]',
                        '---',
                        '### 3 Konsep Inti Deteksi Lanjut',
                        'card:Landmark adalah Geometri:468 titik landmark memberi representasi wajah yang kaya dan ringkas. Ia adalah fondasi verifikasi dan animasi wajah.',
                        'card:Normalisasi adalah Kunci:Konsistensi representasi di berbagai kondisi hanya bisa dicapai dengan normalisasi. IOD adalah salah satu acuan yang paling stabil.',
                        'card:Kemiripan adalah Keputusan:Verifikasi wajah pada akhirnya adalah keputusan ambang. NCC memberi skor, ambang memberi keputusan.',
                        '---',
                        '### Target Kompetensi Pertemuan 6',
                        'skill:100%:Mengekstraksi landmark wajah dengan MediaPipe:Wajib',
                        'skill:95%:Menormalisasi landmark berbasis IOD:Wajib',
                        'skill:90%:Menghitung kemiripan wajah dengan NCC:Wajib',
                        'skill:80%:Menguji stabilitas landmark terhadap jarak dan sudut:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Ekstraksi landmark", "Deskripsi": "Jalankan MediaPipe FaceLandmarker pada webcam, tampilkan 468 titik di canvas"}, {"Aktivitas": "Normalisasi IOD", "Deskripsi": "Normalisasi landmark dari 3 jarak berbeda, bandingkan konsistensi representasi"}, {"Aktivitas": "Uji kemiripan", "Deskripsi": "Ambil landmark dua wajah berbeda, hitung NCC, tentukan ambang verifikasi"}, {"Aktivitas": "Modul landmark", "Deskripsi": "Simpan fungsi landmark dan normalisasi ke vision-core/landmark untuk dipakai ulang"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul07',
                    title: 'Pertemuan 7: Review dan Integrasi P2–P6',
                    lines: [
                        '**Pertemuan 7: Review dan Integrasi P2–P6**',
                        '*Ujian bukan tentang menghafal, tetapi tentang menghubungkan titik-titik yang sudah Anda pelajari.*',
                        '---',
                        'Pertemuan ini adalah jembatan menuju UTS. Kita akan mengulang materi P2–P6 secara terstruktur, mengintegrasikan konsep dari praproses hingga deteksi dan segmentasi, serta berlatih soal-soal yang menuntut pemahaman, bukan hafalan.',
                        'Manfaatkan pertemuan ini untuk mengidentifikasi celah pemahaman Anda sebelum UTS.',
                        '---',
                        '### Yang Sudah Harus Anda Bisa',
                        'card:Membangun Pipeline Lengkap:Dari menangkap frame webcam, praproses, deteksi, hingga menghitung metrik evaluasi — semuanya harus bisa Anda rangkai dalam satu skrip.',
                        'card:Menjelaskan Pilihan Algoritma:Anda harus bisa menjelaskan mengapa memilih Gaussian blur daripada median, mengapa threshold Otsu daripada global, mengapa Haar cascade sebagai baseline.',
                        'card:Menghitung Metrik dengan Tangan:IoU, precision, recall, dan F1 harus bisa Anda hitung manual untuk kasus sederhana, tanpa bergantung pada pustaka.',
                        '---',
                        '### Checklist Persiapan UTS',
                        '```javascript',
                        '// Checklist mandiri sebelum UTS\nconst CHECKLIST = [\n    \'✅ Bisa menangkap frame webcam ke canvas\',\n    \'✅ Bisa menghitung histogram dan ekualisasi\',\n    \'✅ Bisa menerapkan filter Gaussian dan median\',\n    \'✅ Bisa melakukan threshold Otsu dan adaptif\',\n    \'✅ Bisa mendeteksi tepi dengan Canny\',\n    \'✅ Bisa menerapkan operasi morfologi\',\n    \'✅ Bisa menemukan kontur dan menghitung luas\',\n    \'✅ Bisa menjalankan Haar cascade\',\n    \'✅ Bisa menghitung IoU, precision, recall, F1\',\n    \'✅ Bisa mengekstraksi landmark dan normalisasi IOD\'\n];\n\nCHECKLIST.forEach(item => console.log(item));',
                        '```',
                        '---',
                        '### Integration Lab',
                        'Latihan integrasi berikut menggabungkan konsep dari beberapa pertemuan sekaligus. Kerjakan minimal dua di antaranya sebelum UTS.',
                        'table:[{"Skenario": "Pipeline praproses + deteksi", "Menggabungkan": "P3, P4, P5", "Output": "Citra dengan kotak deteksi dan metrik"}, {"Skenario": "Perbandingan detektor", "Menggabungkan": "P4, P5", "Output": "Tabel perbandingan Haar vs CNN"}, {"Skenario": "Landmark + verifikasi", "Menggabungkan": "P6", "Output": "Skor NCC antara dua wajah"}, {"Skenario": "Benchmark lengkap", "Menggabungkan": "P2–P6", "Output": "Laporan latensi dan akurasi"}]',
                        '---',
                        '### 3 Konsep Inti Review',
                        'card:Pipeline adalah Rantai:Setiap tahap praproses memengaruhi kualitas deteksi. Memahami keterkaitan antar tahap adalah kunci menjawab soal UTS.',
                        'card:Metrik adalah Bahasa:UTS akan meminta Anda menghitung dan menafsirkan metrik. Latih tangan Anda, bukan hanya mata Anda.',
                        'card:Integrasi adalah Tujuan:Materi P2–P6 bukan potongan terpisah. UTS menguji kemampuan Anda merangkainya menjadi satu pipeline utuh.',
                        '---',
                        '### Target Kompetensi Pertemuan 7',
                        'skill:100%:Menguasai pipeline praproses hingga deteksi:Wajib',
                        'skill:95%:Menghitung metrik evaluasi secara manual:Wajib',
                        'skill:90%:Menjelaskan trade-off antar algoritma:Wajib',
                        'skill:85%:Menyelesaikan soal integrasi lintas pertemuan:Kesiapan UTS',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Latihan soal terstruktur", "Deskripsi": "Kerjakan 10 soal hitungan metrik dan 5 soal analisis pipeline"}, {"Aktivitas": "Integration lab", "Deskripsi": "Pilih dua skenario integrasi, kerjakan, presentasikan hasil ke kelompok lain"}, {"Aktivitas": "Peer review kode", "Deskripsi": "Review kode pipeline milik kelompok lain, beri masukan konstruktif"}, {"Aktivitas": "Konsolidasi catatan", "Deskripsi": "Susun catatan ringkas satu halaman per pertemuan P2–P6 sebagai bekal UTS"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul08',
                    title: 'Pertemuan 8: UTS — Evaluasi Tengah Semester',
                    lines: [
                        '**Pertemuan 8: UTS — Evaluasi Tengah Semester**',
                        '*Ujian adalah cermin. Ia menunjukkan bukan hanya apa yang Anda tahu, tetapi bagaimana Anda berpikir.*',
                        '---',
                        'UTS mengevaluasi pemahaman Anda atas materi P2–P6: pengantar CV, praproses, praproses lanjut, deteksi dan segmentasi, serta deteksi lanjut. Ujian terdiri dari bagian tertulis dan praktik mini.',
                        'Siapkan diri Anda dengan memahami konsep, bukan menghafal sintaksis. Sintaksis bisa dicari, pemahaman tidak.',
                        '---',
                        '### Strategi Sukses UTS',
                        'card:Kuasai Alur Pipeline:UTS sering meminta Anda menjelaskan urutan tahap dan alasan pemilihannya. Pahami alur, bukan hafal kode.',
                        'card:Latih Hitungan Manual:IoU, precision, recall, dan F1 harus bisa dihitung dengan kertas dan pena. Jangan bergantung pada kalkulator atau pustaka.',
                        'card:Jelaskan Trade-off:Soal analisis menuntut Anda membandingkan algoritma. Siapkan argumen mengapa memilih satu pendekatan daripada yang lain.',
                        '---',
                        '### Rubrik Penilaian UTS',
                        'table:[{"Kriteria": "Pemahaman konsep dasar CV", "Bobot": "20%", "Indikator": "Menjelaskan piksel, warna, canvas, dan alur pipeline"}, {"Kriteria": "Penguasaan praproses", "Bobot": "30%", "Indikator": "Menerapkan filter, threshold, tepi, morfologi dengan tepat"}, {"Kriteria": "Deteksi dan segmentasi", "Bobot": "30%", "Indikator": "Menjalankan detektor, menghitung metrik, menafsirkan hasil"}, {"Kriteria": "Praktik mini", "Bobot": "20%", "Indikator": "Membangun pipeline lengkap dalam waktu terbatas"}]',
                        '---',
                        '### Kerangka Jawaban yang Boleh Dihafal',
                        '```javascript',
                        '// Kerangka jawaban soal pipeline CV\n// 1. Tangkap citra\n//    - webcam → canvas → ImageData\n// 2. Praproses\n//    - grayscale → blur → threshold → morfologi\n// 3. Deteksi / segmentasi\n//    - Haar cascade | kontur | landmark\n// 4. Evaluasi\n//    - IoU → TP/FP/FN → precision/recall/F1\n// 5. Interpretasi\n//    - apa arti angka ini untuk aplikasi?\n\nfunction kerangkaJawabanPipeline() {\n    return [\n        \'Tangkap citra\',\n        \'Praproses\',\n        \'Deteksi atau segmentasi\',\n        \'Evaluasi metrik\',\n        \'Interpretasi hasil\'\n    ];\n}',
                        '```',
                        '---',
                        '### Alokasi Waktu UTS',
                        'skill:30%:Bagian tertulis konsep dasar:54 menit',
                        'skill:40%:Bagian hitungan dan analisis:72 menit',
                        'skill:30%:Praktik mini pipeline:54 menit',
                        '---',
                        '### 3 Konsep Inti UTS',
                        'card:UTS Menguji Pemahaman:Soal tidak akan meminta Anda menghafal sintaksis, tetapi menjelaskan mengapa dan kapan menggunakan suatu teknik.',
                        'card:Metrik adalah Kunci:Separuh nilai UTS bergantung pada kemampuan Anda menghitung dan menafsirkan metrik evaluasi.',
                        'card:Praktik adalah Bukti:Bagian praktik mini menguji apakah Anda benar-benar bisa membangun pipeline, bukan hanya membicarakannya.',
                        '---',
                        '### Target Kompetensi UTS',
                        'skill:100%:Menjelaskan konsep CV dan praproses:Wajib',
                        'skill:100%:Menghitung metrik evaluasi deteksi:Wajib',
                        'skill:95%:Membangun pipeline dalam waktu terbatas:Wajib',
                        'skill:90%:Menganalisis trade-off algoritma:Wajib',
                        '---',
                        '### Aktivitas UTS',
                        'table:[{"Aktivitas": "Bagian tertulis", "Deskripsi": "Soal konsep dan analisis, dikerjakan tanpa komputer"}, {"Aktivitas": "Bagian hitungan", "Deskripsi": "Hitung IoU, precision, recall, F1 dari data yang diberikan"}, {"Aktivitas": "Praktik mini", "Deskripsi": "Bangun pipeline deteksi sederhana di browser dalam waktu 60 menit"}, {"Aktivitas": "Pengumpulan", "Deskripsi": "Kumpulkan jawaban tertulis dan kode praktik melalui repositori masing-masing"}]',
                        '---',
                    ],
                },
            ],
        },
        {
            name: 'Bagian 3: Deskripsi, Pengenalan Pola, dan Pelacakan',
            items: [
                {
                    id: 'modul09',
                    title: 'Pertemuan 9: Deskripsi dan Representasi Objek',
                    lines: [
                        '**Pertemuan 9: Deskripsi dan Representasi Objek**',
                        '*Setelah objek ditemukan, pertanyaannya berubah: bagaimana kita menggambarkannya agar komputer bisa mengenalinya?*',
                        '---',
                        'Pertemuan ini membuka Bagian 3 dengan membahas deskriptor objek: bentuk, kontur, momen, warna, dan tekstur. Anda akan mempelajari bagaimana mengubah objek menjadi vektor fitur yang ringkas dan informatif.',
                        'Materi ini adalah fondasi bagi pengenalan pola dan pelacakan yang akan Anda pelajari di pertemuan berikutnya.',
                        '---',
                        '### Mengapa Deskripsi Objek Penting?',
                        'card:Fitur adalah Bahasa Objek:Komputer tidak bisa membandingkan dua gambar secara langsung. Ia membutuhkan representasi numerik — fitur — yang menangkap esensi objek.',
                        'card:Pemilihan Fitur Menentukan Akurasi:Fitur yang salah membuat objek berbeda tampak mirip, atau objek sama tampak berbeda. Pemilihan fitur adalah seni sekaligus sains.',
                        'card:Representasi adalah Kompresi:Deskriptor yang baik memampatkan informasi objek menjadi vektor kecil tanpa kehilangan informasi penting. Ini krusial untuk efisiensi.',
                        '---',
                        '### Deskriptor Bentuk dan Kontur',
                        'Deskriptor bentuk menggambarkan geometri objek: luas, keliling, rasio aspek, dan momen Hu. Kontur adalah representasi batas objek yang paling umum.',
                        '```javascript',
                        '// Deskriptor bentuk dari kontur\nfunction deskriptorBentuk(kontur) {\n    const luas = cv.contourArea(kontur);\n    const keliling = cv.arcLength(kontur, true);\n    const bounding = cv.boundingRect(kontur);\n    const rasioAspek = bounding.width / bounding.height;\n    const kebulatan = (4 * Math.PI * luas) / (keliling * keliling);\n    return { luas, keliling, rasioAspek, kebulatan };\n}\n\nconst contohKontur = new cv.Mat();\nconsole.log(\'Deskriptor:\', deskriptorBentuk(contohKontur));',
                        '```',
                        '---',
                        '### Momen Hu',
                        'Momen Hu adalah tujuh nilai invarian terhadap translasi, rotasi, dan skala. Mereka adalah deskriptor bentuk yang sangat kuat untuk pengenalan objek.',
                        '```javascript',
                        '// Momen Hu dari kontur\nfunction momenHu(kontur) {\n    const momen = cv.moments(kontur, false);\n    const hu = cv.HuMoments(momen);\n    const hasil = [];\n    for (let i = 0; i < 7; i++) {\n        hasil.push(hu.doubleAt(i, 0));\n    }\n    return hasil;\n}\n\nconsole.log(\'Tujuh momen Hu:\', momenHu(contohKontur).map(v => v.toExponential(2)));',
                        '```',
                        '---',
                        '### Deskriptor Warna dan Tekstur',
                        'Histogram warna adalah deskriptor global yang sederhana namun efektif. Untuk tekstur, Gray Level Co-occurrence Matrix (GLCM) dan Local Binary Pattern (LBP) adalah pilihan umum.',
                        'table:[{"Deskriptor": "Histogram warna", "Dimensi": "3 × 256", "Kelebihan": "Sederhana, cepat, invarian rotasi"}, {"Deskriptor": "Momen Hu", "Dimensi": "7", "Kelebihan": "Invarian translasi, rotasi, skala"}, {"Deskriptor": "HOG", "Dimensi": "Bergantung sel", "Kelebihan": "Menangkap gradien dan bentuk lokal"}, {"Deskriptor": "LBP", "Dimensi": "256", "Kelebihan": "Menangkap tekstur mikro"}]',
                        '---',
                        '### Verifikasi dengan Embedding',
                        'Embedding adalah vektor fitur berdimensi tinggi yang dihasilkan model deep learning. Verifikasi wajah bekerja dengan membandingkan embedding menggunakan ambang tertentu.',
                        '```javascript',
                        '// Verifikasi berbasis ambang\nfunction verifikasi(embeddingA, embeddingB, ambang) {\n    const skor = ncc(embeddingA, embeddingB);\n    const keputusan = skor >= ambang ? \'COCOK\' : \'TIDAK COCOK\';\n    return { skor, keputusan };\n}\n\nconst ambangTerpilih = 0.85;\nconsole.log(\'Ambang verifikasi:\', ambangTerpilih);',
                        '```',
                        '---',
                        '### 3 Konsep Inti Deskripsi Objek',
                        'card:Bentuk adalah Identitas:Deskriptor bentuk seperti momen Hu memberi identitas objek yang invarian terhadap transformasi dasar.',
                        'card:Warna adalah Konteks:Histogram warna memberi konteks global yang cepat dan murah. Ia melengkapi deskriptor bentuk yang hanya melihat geometri.',
                        'card:Embedding adalah Representasi Modern:Embedding deep learning menggantikan fitur tangan dengan representasi yang dipelajari dari data. Ia adalah standar verifikasi wajah modern.',
                        '---',
                        '### Target Kompetensi Pertemuan 9',
                        'skill:100%:Menghitung deskriptor bentuk dan momen Hu:Wajib',
                        'skill:95%:Mengekstraksi histogram warna dan tekstur:Wajib',
                        'skill:90%:Menjelaskan konsep embedding dan ambang verifikasi:Wajib',
                        'skill:80%:Membandingkan deskriptor pada dataset kecil:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Ekstraksi deskriptor", "Deskripsi": "Ambil 5 objek berbeda, ekstraksi luas, keliling, rasio aspek, dan momen Hu"}, {"Aktivitas": "Histogram warna", "Deskripsi": "Hitung histogram R, G, B untuk setiap objek, bandingkan kemiripannya"}, {"Aktivitas": "Uji invariansi", "Deskripsi": "Rotasi dan skala objek, verifikasi momen Hu tetap stabil"}, {"Aktivitas": "Modul verifikasi", "Deskripsi": "Simpan fungsi verifikasi ambang ke vision-core/verify untuk dipakai di P11"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul10',
                    title: 'Pertemuan 10: Deskripsi dan Representasi Objek Lanjut',
                    lines: [
                        '**Pertemuan 10: Deskripsi dan Representasi Objek Lanjut**',
                        '*Fitur lokal adalah detail yang membuat perbedaan. Di situlah identitas sejati sebuah objek tersembunyi.*',
                        '---',
                        'Pertemuan ini memperdalam deskripsi objek dengan fitur lokal: HOG, keypoint, dan landmark. Anda juga akan berkenalan dengan instrumentasi benchmark — mengukur latensi dan FPS sebagai bagian dari representasi kinerja.',
                        'Materi ini menghubungkan deskripsi objek dengan analisis kuantitatif yang akan menjadi tulang punggung proyek Vision Lab.',
                        '---',
                        '### Mengapa Fitur Lokal Penting?',
                        'card:Fitur Global Kehilangan Detail:Histogram warna dan momen Hu merangkum seluruh objek. Fitur lokal menangkap detail di titik-titik kunci yang membedakan objek serupa.',
                        'card:Keypoint Invarian:Keypoint seperti SIFT dan ORB invarian terhadap rotasi dan skala. Mereka adalah fondasi pencocokan citra dan panorama.',
                        'card:Latensi adalah Fitur:Kinerja adalah bagian dari representasi. Model yang akurat tetapi lambat tidak berguna untuk aplikasi real-time. Mengukur latensi adalah keterampilan wajib.',
                        '---',
                        '### HOG — Histogram of Oriented Gradients',
                        'HOG menangkap distribusi gradien lokal dalam sel-sel citra. Ia sangat efektif untuk deteksi pejalan kaki dan objek dengan bentuk khas.',
                        '```javascript',
                        '// HOG sederhana dengan OpenCV.js\nfunction hitungHOG(src) {\n    const gray = new cv.Mat();\n    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);\n    const hog = new cv.HOGDescriptor();\n    const fitur = new cv.Mat();\n    hog.compute(gray, fitur);\n    gray.delete();\n    return fitur;\n}\n\n// Catatan: OpenCV.js mendukung HOGDescriptor untuk deteksi orang\nconsole.log(\'HOG siap dipakai untuk deteksi pejalan kaki\');',
                        '```',
                        '---',
                        '### Keypoint dan ORB',
                        'ORB (Oriented FAST and Rotated BRIEF) adalah detektor keypoint yang cepat dan bebas paten. Ia adalah pilihan populer untuk aplikasi real-time di browser.',
                        '```javascript',
                        '// Deteksi keypoint dengan ORB\nfunction deteksiORB(src) {\n    const gray = new cv.Mat();\n    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);\n    const orb = new cv.ORB(500);\n    const keypoints = new cv.KeyPointVector();\n    const descriptors = new cv.Mat();\n    orb.detectAndCompute(gray, new cv.Mat(), keypoints, descriptors);\n    gray.delete();\n    return { keypoints, descriptors };\n}\n\nconsole.log(\'ORB mendeteksi hingga 500 keypoint per citra\');',
                        '```',
                        '---',
                        '### Instrumentasi Benchmark',
                        'Benchmark adalah proses mengukur kinerja secara sistematis. Dalam Vision Lab, Anda akan mengukur latensi, FPS, dan akurasi pada berbagai skenario.',
                        '```javascript',
                        '// Instrumentasi latensi dan FPS\nfunction ukurLatensi(fn, ulangan = 30) {\n    const waktu = [];\n    for (let i = 0; i < ulangan; i++) {\n        const mulai = performance.now();\n        fn();\n        waktu.push(performance.now() - mulai);\n    }\n    const rata = waktu.reduce((a, b) => a + b, 0) / waktu.length;\n    const fps = 1000 / rata;\n    return { latensiMs: rata, fps };\n}\n\nconsole.log(\'Fungsi ukurLatensi siap dipakai\');',
                        '```',
                        '---',
                        '### 3 Konsep Inti Deskripsi Lanjut',
                        'card:Fitur Lokal adalah Sidik Jari:HOG, ORB, dan landmark menangkap detail lokal yang membedakan objek serupa. Mereka adalah sidik jari digital objek.',
                        'card:Invarian adalah Kunci:Keypoint yang invarian terhadap rotasi dan skala memungkinkan pencocokan citra di berbagai kondisi. Ini adalah fondasi augmented reality dan panorama.',
                        'card:Kinerja adalah Data:Latensi dan FPS bukan opini, melainkan data yang diukur. Instrumentasi yang baik adalah fondasi analisis yang jujur.',
                        '---',
                        '### Target Kompetensi Pertemuan 10',
                        'skill:100%:Mengekstraksi fitur HOG dan keypoint ORB:Wajib',
                        'skill:95%:Mengukur latensi dan FPS secara sistematis:Wajib',
                        'skill:90%:Menjelaskan perbedaan fitur global dan lokal:Wajib',
                        'skill:80%:Merancang skenario benchmark sederhana:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Ekstraksi HOG", "Deskripsi": "Hitung HOG pada 3 citra berbeda, bandingkan vektor fitur yang dihasilkan"}, {"Aktivitas": "Deteksi ORB", "Deskripsi": "Deteksi keypoint ORB pada webcam, tampilkan keypoint di canvas"}, {"Aktivitas": "Benchmark latensi", "Deskripsi": "Ukur latensi deteksi Haar dan ORB pada 30 frame, catat rata-rata dan FPS"}, {"Aktivitas": "Kirim ke D1", "Deskripsi": "Kirim hasil benchmark (library, scenario, latency, fps) ke Worker untuk disimpan"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul11',
                    title: 'Pertemuan 11: Pengenalan Pola',
                    lines: [
                        '**Pertemuan 11: Pengenalan Pola**',
                        '*Mengenali pola berarti mengambil keputusan. Dan setiap keputusan punya konsekuensi — false positive dan false negative.*',
                        '---',
                        'Pertemuan ini membahas klasifikasi dan pengenalan pola: k-NN, ambang, kemiripan, confusion matrix, FAR/FRR, dan kurva ROC. Anda akan belajar mengevaluasi klasifier secara kuantitatif dan menafsirkan hasilnya.',
                        'Materi ini adalah inti dari CPMK-5 dan menjadi fondasi untuk sistem verifikasi dan presensi di proyek Vision Lab.',
                        '---',
                        '### Mengapa Pengenalan Pola Penting?',
                        'card:Klasifikasi adalah Keputusan:Setiap aplikasi CV pada akhirnya membuat keputusan: ini wajah siapa, ini objek apa, ini termasuk kelas mana. Klasifikasi adalah jantung keputusan itu.',
                        'card:Confusion Matrix adalah Cermin:Confusion matrix menunjukkan bukan hanya berapa banyak yang benar, tetapi jenis kesalahan apa yang terjadi. Ini krusial untuk aplikasi kritis.',
                        'card:FAR dan FRR adalah Trade-off:False Acceptance Rate dan False Rejection Rate tidak bisa diminimalkan bersamaan. Memilih ambang adalah memilih trade-off.',
                        '---',
                        '### Klasifikasi dengan k-NN',
                        'k-Nearest Neighbors adalah klasifier sederhana yang bekerja dengan mencari tetangga terdekat dalam ruang fitur. Ia adalah baseline yang baik untuk memahami konsep klasifikasi.',
                        '```javascript',
                        '// Klasifikasi k-NN sederhana\nfunction knn(latih, uji, k = 3) {\n    const jarak = latih.map(item => ({\n        label: item.label,\n        d: Math.hypot(item.x - uji.x, item.y - uji.y)\n    }));\n    jarak.sort((a, b) => a.d - b.d);\n    const tetangga = jarak.slice(0, k);\n    const suara = {};\n    tetangga.forEach(t => suara[t.label] = (suara[t.label] || 0) + 1);\n    return Object.entries(suara).sort((a, b) => b[1] - a[1])[0][0];\n}\n\nconst dataLatih = [\n    { x: 1, y: 2, label: \'A\' },\n    { x: 2, y: 3, label: \'A\' },\n    { x: 8, y: 9, label: \'B\' },\n    { x: 9, y: 8, label: \'B\' }\n];\nconsole.log(\'Prediksi:\', knn(dataLatih, { x: 3, y: 4 }));',
                        '```',
                        '---',
                        '### Confusion Matrix dan Metrik',
                        'Confusion matrix merangkum performa klasifier dalam empat sel: True Positive, False Positive, True Negative, dan False Negative.',
                        'table:[{"Metrik": "Akurasi", "Rumus": "(TP + TN) / Total", "Makna": "Proporsi prediksi benar secara keseluruhan"}, {"Metrik": "Precision", "Rumus": "TP / (TP + FP)", "Makna": "Dari yang diprediksi positif, berapa yang benar"}, {"Metrik": "Recall", "Rumus": "TP / (TP + FN)", "Makna": "Dari yang sebenarnya positif, berapa yang tertangkap"}, {"Metrik": "F1", "Rumus": "2 × P × R / (P + R)", "Makna": "Rata-rata harmonik precision dan recall"}]',
                        '```javascript',
                        '// Menghitung metrik dari confusion matrix\nfunction metrik(tp, fp, fn, tn) {\n    const akurasi = (tp + tn) / (tp + fp + fn + tn);\n    const precision = tp / (tp + fp);\n    const recall = tp / (tp + fn);\n    const f1 = 2 * (precision * recall) / (precision + recall);\n    return { akurasi, precision, recall, f1 };\n}\n\nconst hasil = metrik(80, 10, 5, 105);\nconsole.log(\'Akurasi:\', (hasil.akurasi * 100).toFixed(1) + \'%\');\nconsole.log(\'F1:\', hasil.f1.toFixed(3));',
                        '```',
                        '---',
                        '### FAR, FRR, dan Kurva ROC',
                        'FAR (False Acceptance Rate) adalah proporsi impostor yang diterima. FRR (False Rejection Rate) adalah proporsi pengguna sah yang ditolak. Kurva ROC memvisualisasikan trade-off antara keduanya.',
                        '```javascript',
                        '// FAR dan FRR dari data verifikasi\nfunction farFrr(skor, label, ambang) {\n    let fa = 0, fr = 0, totalImpostor = 0, totalGenuine = 0;\n    for (let i = 0; i < skor.length; i++) {\n        const diterima = skor[i] >= ambang;\n        if (label[i] === 1) {\n            totalGenuine++;\n            if (!diterima) fr++;\n        } else {\n            totalImpostor++;\n            if (diterima) fa++;\n        }\n    }\n    return {\n        far: fa / totalImpostor,\n        frr: fr / totalGenuine\n    };\n}\n\nconsole.log(\'FAR dan FRR dihitung dari data skor verifikasi\');',
                        '```',
                        '---',
                        '### 3 Konsep Inti Pengenalan Pola',
                        'card:Klasifikasi adalah Keputusan:Setiap klasifier membuat keputusan berdasarkan fitur. Memahami cara kerja klasifier berarti memahami cara keputusan diambil.',
                        'card:Confusion Matrix adalah Diagnosis:Confusion matrix tidak hanya menunjukkan akurasi, tetapi jenis kesalahan. Ini krusial untuk aplikasi medis dan keamanan.',
                        'card:Ambang adalah Kebijakan:Memilih ambang verifikasi bukan keputusan teknis semata, melainkan kebijakan yang mempertimbangkan risiko dan kenyamanan pengguna.',
                        '---',
                        '### Target Kompetensi Pertemuan 11',
                        'skill:100%:Menerapkan klasifikasi k-NN dan ambang:Wajib',
                        'skill:100%:Menghitung dan menafsirkan confusion matrix:Wajib',
                        'skill:95%:Menghitung FAR, FRR, dan menggambar kurva ROC:Wajib',
                        'skill:85%:Memilih ambang verifikasi berdasarkan trade-off:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Klasifikasi k-NN", "Deskripsi": "Bangun dataset fitur sederhana, klasifikasikan dengan k-NN, evaluasi akurasi"}, {"Aktivitas": "Confusion matrix", "Deskripsi": "Hitung confusion matrix dari hasil deteksi, hitung precision, recall, F1"}, {"Aktivitas": "Kurva ROC", "Deskripsi": "Plot FAR vs FRR untuk berbagai ambang, tentukan ambang optimal"}, {"Aktivitas": "Modul verifikasi", "Deskripsi": "Simpan fungsi verifikasi dan ambang terkalibrasi ke vision-core/verify"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul12',
                    title: 'Pertemuan 12: Pelacakan Objek',
                    lines: [
                        '**Pertemuan 12: Pelacakan Objek**',
                        '*Deteksi memberi snapshot. Pelacakan memberi cerita — bagaimana objek bergerak dari waktu ke waktu.*',
                        '---',
                        'Pertemuan ini membahas pelacakan objek: tracking-by-detection, Kalman filter, dan asosiasi berbasis IoU. Anda akan membangun tracker sederhana yang mampu mengikuti objek di video.',
                        'Materi ini menutup Bagian 3 dan menjadi jembatan ke aplikasi di Bagian 4, termasuk simulasi robotik dan analisis gerak.',
                        '---',
                        '### Mengapa Pelacakan Objek Penting?',
                        'card:Video adalah Urutan Waktu:Deteksi per frame tidak cukup. Pelacakan menghubungkan deteksi antar frame menjadi lintasan yang bermakna.',
                        'card:Kalman Filter adalah Prediktor:Kalman filter memprediksi posisi objek berikutnya berdasarkan posisi saat ini dan kecepatannya. Ia adalah alat fundamental pelacakan.',
                        'card:Asosiasi adalah Kunci:Menghubungkan deteksi baru dengan lintasan yang sudah ada adalah masalah asosiasi. IoU adalah metrik yang paling umum dipakai.',
                        '---',
                        '### Tracking-by-Detection',
                        'Tracking-by-detection adalah paradigma paling umum: deteksi objek di setiap frame, lalu asosiasikan deteksi antar frame berdasarkan kemiripan posisi.',
                        '```javascript',
                        '// Tracking-by-detection sederhana\nclass TrackerSederhana {\n    constructor(iouThreshold = 0.3) {\n        this.tracks = [];\n        this.iouThreshold = iouThreshold;\n        this.nextId = 1;\n    }\n\n    update(deteksi) {\n        const terpakai = new Set();\n        for (const track of this.tracks) {\n            let terbaik = null;\n            let iouTerbaik = this.iouThreshold;\n            for (let i = 0; i < deteksi.length; i++) {\n                if (terpakai.has(i)) continue;\n                const iou = hitungIoU(track.box, deteksi[i]);\n                if (iou > iouTerbaik) {\n                    iouTerbaik = iou;\n                    terbaik = i;\n                }\n            }\n            if (terbaik !== null) {\n                track.box = deteksi[terbaik];\n                terpakai.add(terbaik);\n            }\n        }\n        for (let i = 0; i < deteksi.length; i++) {\n            if (!terpakai.has(i)) {\n                this.tracks.push({ id: this.nextId++, box: deteksi[i] });\n            }\n        }\n        return this.tracks;\n    }\n}',
                        '```',
                        '---',
                        '### Kalman Filter',
                        'Kalman filter adalah algoritma estimasi yang memprediksi state objek (posisi, kecepatan) berdasarkan pengukuran yang berisik. Ia adalah standar dalam pelacakan objek.',
                        '```javascript',
                        '// Kalman filter 1D sederhana (posisi + kecepatan)\nclass Kalman1D {\n    constructor() {\n        this.x = 0;\n        this.v = 0;\n        this.p = 1;\n        this.q = 0.01;\n        this.r = 0.1;\n    }\n\n    prediksi(dt = 1) {\n        this.x = this.x + this.v * dt;\n        this.p = this.p + this.q;\n        return this.x;\n    }\n\n    koreksi(z) {\n        const k = this.p / (this.p + this.r);\n        this.x = this.x + k * (z - this.x);\n        this.p = (1 - k) * this.p;\n        return this.x;\n    }\n}\n\nconst kf = new Kalman1D();\nkf.prediksi();\nkf.koreksi(10);\nconsole.log(\'Estimasi posisi:\', kf.x.toFixed(2));',
                        '```',
                        '---',
                        '### Asosiasi Berbasis IoU',
                        'Asosiasi adalah proses mencocokkan deteksi baru dengan lintasan yang ada. IoU adalah metrik yang paling umum, tetapi Hungarian algorithm dan cosine similarity juga dipakai.',
                        'table:[{"Metode": "IoU", "Kelebihan": "Sederhana dan cepat", "Keterbatasan": "Gagal saat objek bergerak cepat"}, {"Metode": "Hungarian", "Kelebihan": "Optimal secara global", "Keterbatasan": "Kompleksitas lebih tinggi"}, {"Metode": "Cosine similarity", "Kelebihan": "Bekerja pada ruang fitur", "Keterbatasan": "Perlu embedding"}, {"Metode": "Kalman + IoU", "Kelebihan": "Prediksi + asosiasi", "Keterbatasan": "Perlu tuning parameter"}]',
                        '---',
                        '### 3 Konsep Inti Pelacakan Objek',
                        'card:Tracking adalah Asosiasi:Pelacakan pada dasarnya adalah masalah mencocokkan deteksi antar frame. Semakin baik asosiasi, semakin stabil lintasan.',
                        'card:Kalman adalah Prediktor:Kalman filter memprediksi posisi berikutnya, sehingga tracker tidak bergantung sepenuhnya pada deteksi yang berisik.',
                        'card:IoU adalah Kompromi:IoU adalah metrik asosiasi yang sederhana namun efektif. Ia adalah titik awal yang baik sebelum beralih ke metode yang lebih kompleks.',
                        '---',
                        '### Target Kompetensi Pertemuan 12',
                        'skill:100%:Membangun tracker sederhana berbasis IoU:Wajib',
                        'skill:95%:Menerapkan Kalman filter untuk prediksi posisi:Wajib',
                        'skill:90%:Menjelaskan trade-off metode asosiasi:Wajib',
                        'skill:80%:Menguji tracker pada rekaman video:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Tracker IoU", "Deskripsi": "Bangun tracker sederhana, uji pada deteksi wajah dari webcam"}, {"Aktivitas": "Kalman filter", "Deskripsi": "Terapkan Kalman filter pada lintasan objek, bandingkan dengan tanpa filter"}, {"Aktivitas": "Uji video", "Deskripsi": "Rekam video pendek, jalankan tracker, evaluasi stabilitas lintasan"}, {"Aktivitas": "Modul tracker", "Deskripsi": "Simpan kelas Tracker ke vision-core/tracker untuk dipakai di P14"}]',
                        '---',
                    ],
                },
            ],
        },

                {
            name: 'Bagian 4: Aplikasi dan Evaluasi Akhir',
            items: [
                {
                    id: 'modul13',
                    title: 'Pertemuan 13: Aplikasi Computer Vision',
                    lines: [
                        '**Pertemuan 13: Aplikasi Computer Vision**',
                        '*Teori menjadi bermakna ketika ia menyentuh kehidupan nyata — wajah yang dikenali, penyakit yang terdeteksi, robot yang bergerak.*',
                        '---',
                        'Pertemuan ini membuka Bagian 4 dengan menjelajahi aplikasi nyata Computer Vision: pengenalan wajah, citra medis, kendali robotik, dan pengawasan industri. Anda juga akan berkenalan dengan model modern seperti ViT, segmentasi SAM, dan ONNX Runtime Web.',
                        'Materi ini menghubungkan semua yang telah Anda pelajari dengan dunia industri dan penelitian, sekaligus mempersiapkan demo proyek akhir.',
                        '---',
                        '### Mengapa Aplikasi Nyata Penting?',
                        'card:CV Mengubah Industri:Pengenalan wajah mengamankan akses, citra medis mendeteksi kanker lebih awal, kendali robotik mengotomatiskan pabrik, dan pengawasan industri menjaga kualitas produk.',
                        'card:Model Modern Membuka Peluang:ViT, SAM, dan ONNX Runtime Web memungkinkan model canggih berjalan di browser tanpa server. Ini adalah lompatan besar untuk aplikasi web.',
                        'card:Etika adalah Tanggung Jawab:Pengenalan wajah membawa risiko privasi. Setiap aplikasi harus dirancang dengan prinsip minimalisasi data dan persetujuan pengguna.',
                        '---',
                        '### Pengenalan Wajah',
                        'Pengenalan wajah adalah aplikasi CV paling populer. Ia menggabungkan deteksi, landmark, embedding, dan verifikasi menjadi satu pipeline.',
                        '```javascript',
                        '// Pipeline pengenalan wajah lengkap\nasync function pipelinePengenalanWajah(frame) {\n    // 1. Deteksi wajah\n    const wajah = await deteksiWajah(frame);\n    if (wajah.length === 0) return { status: \'tidak ada wajah\' };\n\n    // 2. Ekstraksi landmark\n    const landmark = await ambilLandmark(frame, wajah[0]);\n\n    // 3. Normalisasi IOD\n    const ternormalisasi = normalisasiIOD(landmark);\n\n    // 4. Hitung embedding\n    const embedding = hitungEmbedding(ternormalisasi);\n\n    // 5. Verifikasi\n    const hasil = verifikasi(embedding, embeddingTerdaftar, ambangTerpilih);\n\n    return { status: hasil.keputusan, skor: hasil.skor };\n}\n\nconsole.log(\'Pipeline pengenalan wajah siap dipakai\');',
                        '```',
                        '---',
                        '### Citra Medis',
                        'Di bidang medis, CV membantu radiolog mendeteksi kelainan pada X-ray, CT scan, dan MRI. Tantangan utamanya adalah data yang terbatas dan konsekuensi kesalahan yang tinggi.',
                        '```javascript',
                        '// Segmentasi citra medis (konsep)\nfunction segmentasiMedis(src) {\n    // Praproses: normalisasi intensitas\n    const normal = new cv.Mat();\n    src.convertTo(normal, cv.CV_32F, 1 / 255);\n\n    // Segmentasi: threshold adaptif\n    const biner = new cv.Mat();\n    cv.adaptiveThreshold(normal, biner, 255,\n        cv.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY, 11, 2);\n\n    return biner;\n}\n\nconsole.log(\'Segmentasi medis: hati-hati dengan kesalahan false negative\');',
                        '```',
                        '---',
                        '### Kendali Robotik dan Pengawasan Industri',
                        'Kendali robotik menggunakan CV untuk visual servoing: robot bergerak berdasarkan posisi objek yang terdeteksi. Pengawasan industri menggunakan CV untuk inspeksi kualitas otomatis.',
                        'table:[{"Aplikasi": "Pengenalan wajah", "Teknologi": "MediaPipe, face-api.js", "Tantangan": "Privasi, spoofing"}, {"Aplikasi": "Citra medis", "Teknologi": "CNN, U-Net", "Tantangan": "Data terbatas, akurasi tinggi"}, {"Aplikasi": "Kendali robotik", "Teknologi": "Visual servoing, Kalman", "Tantangan": "Real-time, latensi rendah"}, {"Aplikasi": "Pengawasan industri", "Teknologi": "Deteksi objek, segmentasi", "Tantangan": "Variasi pencahayaan, kecepatan"}]',
                        '---',
                        '### Model Modern di Browser',
                        'ViT (Vision Transformer), SAM (Segment Anything Model), dan ONNX Runtime Web membawa model canggih ke browser. Tantangannya adalah ukuran model dan latensi.',
                        '```javascript',
                        '// Menjalankan model ONNX di browser (konsep)\n// import * as ort from \'onnxruntime-web\';\n\nasync function muatModelONNX(path) {\n    const session = await ort.InferenceSession.create(path, {\n        executionProviders: [\'wasm\']\n    });\n    return session;\n}\n\nasync function inferensiONNX(session, input) {\n    const tensor = new ort.Tensor(\'float32\', input, [1, 3, 224, 224]);\n    const hasil = await session.run({ input: tensor });\n    return hasil.output.data;\n}\n\nconsole.log(\'ONNX Runtime Web memungkinkan inferensi model di browser\');',
                        '```',
                        '---',
                        '### 3 Konsep Inti Aplikasi CV',
                        'card:Pipeline adalah Produk:Aplikasi CV adalah pipeline yang dirangkai dari komponen yang sudah Anda pelajari. Menguasai pipeline berarti menguasai aplikasi.',
                        'card:Model Modern Membuka Batas:ViT, SAM, dan ONNX Runtime Web memungkinkan model canggih berjalan di browser. Ini adalah peluang besar untuk aplikasi web inovatif.',
                        'card:Etika adalah Fondasi:Aplikasi CV yang melibatkan data pribadi harus dirancang dengan prinsip privasi sejak awal. Etika bukan tambahan, melainkan fondasi.',
                        '---',
                        '### Target Kompetensi Pertemuan 13',
                        'skill:100%:Menjelaskan aplikasi CV di berbagai domain:Wajib',
                        'skill:95%:Merangkai pipeline pengenalan wajah lengkap:Wajib',
                        'skill:90%:Menjalankan model modern di browser:Wajib',
                        'skill:80%:Menganalisis tantangan etika dan teknis aplikasi:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Pipeline pengenalan wajah", "Deskripsi": "Rangkai deteksi, landmark, embedding, verifikasi menjadi satu fungsi"}, {"Aktivitas": "Eksperimen model modern", "Deskripsi": "Jalankan satu model ONNX di browser, ukur latensi dan akurasi"}, {"Aktivitas": "Studi kasus aplikasi", "Deskripsi": "Pilih satu domain (medis, robotik, industri), analisis tantangan dan solusinya"}, {"Aktivitas": "Run tambahan ke D1", "Deskripsi": "Kirim hasil eksperimen model modern ke Worker untuk disimpan"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul14',
                    title: 'Pertemuan 14: Aplikasi Computer Vision Lanjut',
                    lines: [
                        '**Pertemuan 14: Aplikasi Computer Vision Lanjut**',
                        '*Setiap sistem yang kuat juga memiliki kelemahan. Mengenali kelemahan adalah langkah pertama menuju ketahanan.*',
                        '---',
                        'Pertemuan ini memperdalam aplikasi CV dengan pengantar deep learning, inferensi di browser, etika data biometrik, serta ketahanan dan keamanan sistem. Anda akan mempelajari adversarial attack, spoofing, dan prinsip privasi sesuai UU PDP.',
                        'Materi ini adalah pertemuan teknis terakhir sebelum Final Review dan UAS, dan menjadi bekal untuk demo proyek terpadu.',
                        '---',
                        '### Mengapa Ketahanan dan Etika Penting?',
                        'card:Sistem Rentan Diserang:Adversarial attack dapat menipu model CV dengan perubahan kecil yang tidak terlihat mata manusia. Spoofing dapat menipu sistem pengenalan wajah dengan foto atau video.',
                        'card:Privasi adalah Hak:Data biometrik dilindungi UU PDP No. 27/2022. Sistem CV harus dirancang dengan prinsip minimalisasi data, persetujuan, dan transparansi.',
                        'card:Deep Learning adalah Alat:Deep learning bukan tujuan, melainkan alat. Memahami kapan menggunakannya dan kapan tidak adalah keterampilan yang lebih penting daripada sekadar menggunakannya.',
                        '---',
                        '### Pengantar Deep Learning untuk CV',
                        'Deep learning menggantikan fitur tangan dengan representasi yang dipelajari dari data. CNN adalah arsitektur dasar untuk CV, diikuti ViT untuk tugas yang lebih kompleks.',
                        '```javascript',
                        '// Arsitektur CNN sederhana (konsep)\n// Input → Conv → Pool → Conv → Pool → Flatten → Dense → Output\n\nconst ARSITEKTUR_CNN = {\n    input: \'224x224x3\',\n    lapisan: [\n        { tipe: \'conv\', filter: 32, kernel: 3 },\n        { tipe: \'pool\', ukuran: 2 },\n        { tipe: \'conv\', filter: 64, kernel: 3 },\n        { tipe: \'pool\', ukuran: 2 },\n        { tipe: \'flatten\' },\n        { tipe: \'dense\', unit: 128 },\n        { tipe: \'output\', unit: 10 }\n    ]\n};\n\nconsole.log(\'Lapisan CNN:\', ARSITEKTUR_CNN.lapisan.length);',
                        '```',
                        '---',
                        '### Inferensi di Browser',
                        'Inferensi di browser menghilangkan kebutuhan server, mengurangi latensi jaringan, dan menjaga privasi data. Tantangannya adalah keterbatasan komputasi dan ukuran model.',
                        '```javascript',
                        '// Perbandingan backend inferensi di browser\nconst BACKEND = {\n    wasm: { kecepatan: \'sedang\', kompatibilitas: \'luas\', cocok: \'CPU\' },\n    webgl: { kecepatan: \'tinggi\', kompatibilitas: \'luas\', cocok: \'GPU\' },\n    webgpu: { kecepatan: \'sangat tinggi\', kompatibilitas: \'terbatas\', cocok: \'GPU modern\' }\n};\n\nconsole.log(\'Pilih backend sesuai perangkat target\');',
                        '```',
                        '---',
                        '### Adversarial Attack dan Spoofing',
                        'Adversarial attack memanipulasi input untuk menipu model. Spoofing menipu sistem pengenalan wajah dengan foto, video, atau topeng. Mitigasi mencakup liveness detection dan adversarial training.',
                        '```javascript',
                        '// Deteksi liveness sederhana (konsep)\nfunction deteksiLiveness(frame1, frame2) {\n    // Wajah asli memiliki perubahan mikro (kedipan, gerakan)\n    // Wajah palsu (foto) tidak berubah\n    const perbedaan = hitungPerbedaan(frame1, frame2);\n    if (perbedaan < 0.01) {\n        return { hidup: false, alasan: \'tidak ada gerakan mikro\' };\n    }\n    return { hidup: true, alasan: \'gerakan mikro terdeteksi\' };\n}\n\nconsole.log(\'Liveness detection mencegah spoofing foto\');',
                        '```',
                        '---',
                        '### Etika dan UU PDP',
                        'UU PDP No. 27/2022 mengatur perlindungan data pribadi, termasuk data biometrik. Prinsip utamanya: minimalisasi data, persetujuan eksplisit, dan hak subjek data.',
                        'table:[{"Prinsip": "Minimalisasi data", "Penerapan": "Hanya simpan metrik, bukan citra mentah"}, {"Prinsip": "Persetujuan eksplisit", "Penerapan": "Lembar persetujuan sebelum merekam wajah"}, {"Prinsip": "Hak subjek data", "Penerapan": "Mekanisme hapus data atas permintaan"}, {"Prinsip": "Transparansi", "Penerapan": "Jelaskan cara data dipakai dan disimpan"}]',
                        '---',
                        '### 3 Konsep Inti Aplikasi Lanjut',
                        'card:Deep Learning adalah Alat:CNN, ViT, dan model modern adalah alat untuk mencapai tujuan. Pahami kapan menggunakannya, bukan hanya cara menggunakannya.',
                        'card:Inferensi di Browser adalah Pilihan:Menjalankan model di browser mengurangi latensi dan menjaga privasi. Pilih backend sesuai perangkat target.',
                        'card:Etika adalah Hukum:UU PDP bukan sekadar pedoman, melainkan hukum yang mengikat. Sistem CV harus dirancang dengan kepatuhan sejak awal.',
                        '---',
                        '### Target Kompetensi Pertemuan 14',
                        'skill:100%:Menjelaskan arsitektur CNN dan ViT:Wajib',
                        'skill:95%:Menjalankan inferensi model di browser:Wajib',
                        'skill:90%:Mengidentifikasi risiko adversarial dan spoofing:Wajib',
                        'skill:85%:Menerapkan prinsip UU PDP dalam desain sistem:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Inferensi model", "Deskripsi": "Jalankan satu model CNN atau ViT di browser, ukur latensi per backend"}, {"Aktivitas": "Uji spoofing", "Deskripsi": "Coba tipu sistem pengenalan wajah dengan foto cetak atau layar, catat hasilnya"}, {"Aktivitas": "Mitigasi liveness", "Deskripsi": "Implementasikan deteksi liveness sederhana, uji pada wajah asli vs foto"}, {"Aktivitas": "Laporan ancaman", "Deskripsi": "Susun laporan ancaman CV untuk proyek Vision Lab, termasuk mitigasi dan kepatuhan UU PDP"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul15',
                    title: 'Pertemuan 15: Final Review dan Demo P9–P14',
                    lines: [
                        '**Pertemuan 15: Final Review dan Demo P9–P14**',
                        '*Perjalanan panjang layak dirayakan — tetapi juga layak diuji. Inilah saatnya menunjukkan apa yang telah Anda bangun.*',
                        '---',
                        'Pertemuan ini adalah final review dan demo proyek. Kita akan mengulang materi P9–P14, meninjau kembali perjalanan semester, dan mempersiapkan demo terpadu untuk UAS.',
                        'Manfaatkan pertemuan ini untuk menyempurnakan proyek Vision Lab dan memastikan semua artefak siap dinilai.',
                        '---',
                        '### Apa yang Harus Bisa Didemonstrasikan',
                        'card:Pipeline Lengkap:Dari menangkap frame hingga verifikasi wajah, pipeline harus berjalan lancar di browser tanpa error.',
                        'card:Data Terukur:Semua hasil harus tercatat di D1 — latensi, akurasi, metrik evaluasi. Demo tanpa data bukan demo, melainkan klaim.',
                        'card:Dokumentasi Lengkap:Repo harus memiliki README, dokumentasi API, dan CITATION.cff. Dokumentasi adalah bagian dari produk.',
                        '---',
                        '### Rubrik Penilaian Final Review',
                        'table:[{"Komponen": "Fungsionalitas pipeline", "Bobot": "30%", "Indikator": "Pipeline berjalan tanpa error, semua tahap terhubung"}, {"Komponen": "Kualitas data dan analisis", "Bobot": "25%", "Indikator": "Data tercatat di D1, analisis statistik valid"}, {"Komponen": "Dokumentasi dan repo", "Bobot": "20%", "Indikator": "README, dokumentasi API, CITATION.cff lengkap"}, {"Komponen": "Presentasi dan demo", "Bobot": "25%", "Indikator": "Demo lancar, penjelasan jelas, tanya jawab memuaskan"}]',
                        '---',
                        '### Kilas Balik Perjalanan Semester',
                        'card:Bagian 1 — Fondasi:Anda belajar piksel, warna, canvas, praproses, filter, threshold, tepi, dan morfologi. Ini adalah fondasi yang membuat semua tahap berikutnya mungkin.',
                        'card:Bagian 2 — Deteksi dan Segmentasi:Anda belajar menemukan objek, mengekstraksi kontur, menjalankan detektor klasik dan CNN, serta menghitung metrik evaluasi.',
                        'card:Bagian 3 — Deskripsi dan Pelacakan:Anda belajar menggambarkan objek dengan fitur, mengenali pola, dan melacak objek dalam video. Ini adalah inti kecerdasan CV.',
                        '---',
                        '### Kriteria Kelulusan',
                        'skill:100%:Pipeline berjalan tanpa error di browser:Wajib',
                        'skill:95%:Data tercatat dan dianalisis dengan benar:Wajib',
                        'skill:90%:Dokumentasi lengkap dan rapi:Wajib',
                        'skill:85%:Presentasi jelas dan meyakinkan:Wajib',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Peer review PR", "Deskripsi": "Review pull request kelompok lain, beri masukan konstruktif"}, {"Aktivitas": "Demo internal", "Deskripsi": "Demo pipeline ke kelompok lain, kumpulkan umpan balik"}, {"Aktivitas": "Perbaikan akhir", "Deskripsi": "Perbaiki bug dan dokumentasi berdasarkan umpan balik"}, {"Aktivitas": "Rilis v1.0", "Deskripsi": "Buat tag v1.0 di repo, arsipkan artefak, siapkan CITATION.cff"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul16',
                    title: 'UAS: Demo Terpadu Vision Lab',
                    lines: [
                        '**UAS: Demo Terpadu Vision Lab**',
                        '*Inilah puncak perjalanan — saatnya menunjukkan bahwa Anda bukan hanya belajar, tetapi membangun.*',
                        '---',
                        'UAS adalah demo terpadu proyek Vision Lab. Anda akan mempresentasikan pipeline lengkap, data yang tercatat di D1, dan analisis yang Anda lakukan sepanjang semester.',
                        'Ujian ini mengevaluasi materi P9–P14 dan kemampuan Anda mengintegrasikan semua yang telah dipelajari.',
                        '---',
                        '### Apa yang Membedakan dari UTS',
                        'card:UAS Menuntut Integrasi:UTS menguji pemahaman konsep. UAS menguji kemampuan merangkai semua konsep menjadi sistem yang berjalan.',
                        'card:UAS Menuntut Data:UTS cukup dengan jawaban benar. UAS menuntut bukti — data di D1, grafik analisis, dan metrik yang terukur.',
                        'card:UAS Menuntut Presentasi:UTS dinilai dari lembar jawaban. UAS dinilai dari kemampuan Anda menjelaskan dan mempertahankan karya di depan penguji.',
                        '---',
                        '### Arsitektur Vision Lab',
                        '```javascript',
                        '// Arsitektur lengkap Vision Lab\n// Browser (PWA)\n//   kamera → canvas → inferensi WASM\n//   (OpenCV.js | face-api | MediaPipe)\n//   antrean offline (IndexedDB)\n//        ↓\n// Cloudflare Worker\n//   POST /api/runs\n//   POST /api/detections\n//   GET  /api/experiments/:id/summary\n//        ↓\n// D1 (SQLite)\n//   users | experiments | runs | detections | audit_log\n\nconst ARSITEKTUR = {\n    klien: [\'kamera\', \'canvas\', \'inferensi WASM\', \'IndexedDB\'],\n    server: [\'Worker\', \'validasi JWT\', \'RBAC\'],\n    data: [\'runs\', \'detections\', \'experiments\']\n};\n\nconsole.log(\'Arsitektur Vision Lab siap didemokan\');',
                        '```',
                        '---',
                        '### Fitur Kunci yang Harus Ada',
                        '```javascript',
                        '// Fitur kunci Vision Lab\nconst FITUR = {\n    deteksi: [\'Haar cascade\', \'BlazeFace\', \'MediaPipe\'],\n    verifikasi: [\'landmark\', \'normalisasi IOD\', \'NCC\', \'ambang FAR/FRR\'],\n    benchmark: [\'latensi\', \'FPS\', \'akurasi\', \'perbandingan pustaka\'],\n    data: [\'runs\', \'detections\', \'summary\', \'ekspor laporan\'],\n    etika: [\'persetujuan\', \'minimalisasi data\', \'audit log\']\n};\n\nconsole.log(\'Fitur yang harus didemokan:\', Object.keys(FITUR));',
                        '```',
                        '---',
                        '### Rubrik Penilaian UAS',
                        'table:[{"No": "1", "Kriteria": "Fungsionalitas pipeline", "Bobot": "25%", "Deskripsi": "Pipeline berjalan tanpa error, semua tahap terhubung"}, {"No": "2", "Kriteria": "Kualitas data dan analisis", "Bobot": "25%", "Deskripsi": "Data tercatat di D1, analisis statistik valid dan bermakna"}, {"No": "3", "Kriteria": "Inovasi dan kedalaman", "Bobot": "20%", "Deskripsi": "Ada fitur tambahan atau analisis yang melampaui dasar"}, {"No": "4", "Kriteria": "Dokumentasi dan repo", "Bobot": "15%", "Deskripsi": "README, dokumentasi API, CITATION.cff lengkap"}, {"No": "5", "Kriteria": "Presentasi dan demo", "Bobot": "15%", "Deskripsi": "Demo lancar, penjelasan jelas, tanya jawab memuaskan"}]',
                        '---',
                        '### Target Kualitas',
                        'skill:100%:Pipeline berjalan tanpa error di browser:Wajib',
                        'skill:95%:Data tercatat dan dianalisis dengan benar:Wajib',
                        'skill:90%:Dokumentasi lengkap dan rapi:Wajib',
                        'skill:85%:Presentasi jelas dan meyakinkan:Wajib',
                        '---',
                        '### Tips Terakhir',
                        'card:Lakukan Dry Run:Demo yang lancar adalah hasil latihan. Lakukan dry run minimal dua kali sebelum demo sesungguhnya.',
                        'card:Siapkan Fallback:Jika koneksi internet gagal, siapkan video rekaman demo sebagai cadangan. Jangan bergantung pada satu jalur.',
                        'card:Jawab dengan Data:Setiap pertanyaan penguji sebaiknya dijawab dengan data — angka, grafik, atau metrik. Hindari jawaban spekulatif.',
                        '---',
                    ],
                },
            ],
        },
    ],
};
        
        
